version: '3'

services:
  #Mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data
      - ./backup:/home
    expose:
      - 27017
    ports:
      - 27017:27017
    command: [--auth]
    networks:
      - app-network

  #Redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    tty: true
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./cache-redis:/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
