export const HASH_SALT = 10;
//socket
export const SOCKET_LIKE_CREATED = 'SOCKET_LIKE_CREATED';
export const SOCKET_LIKE_DELETED = 'SOCKET_LIKE_DELETED';
export const SOCKET_MY_LIBRARY_ADD_THIS_SONG =
  'SOCKET_MY_LIBRARY_ADD_THIS_SONG';
export const SOCKET_MY_LIBRARY_REMOVE_THIS_SONG =
  'SOCKET_MY_LIBRARY_REMOVE_THIS_SONG';
